## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Location chalet - Les cimes blanches"
theme = "hugo-story"
copyright = 'IMMOCIMES ©'
defaultContentLanguage = 'fr'

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
googleAnalytics = "G-3PTDF9WRWB"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Location de chalet dans les Hautes Vosges (88) | belles prestations | Les Cimes Blanches."
  logo = "images/logo-lcb-grey.png"
  favicon = true
  keywords = "location chalet, location vosges, location la bresse, chalet vosges, vacances montagne, weekend montagne, weekend vosges, chalet jacuzzi, vosges spa, vosge jacuzzi"

[Params.social]
  airbnb = "https://www.airbnb.fr/rooms/643284240513655945"
  facebook = "https://www.facebook.com/Chalet-Les-cimes-blanches-108544971906237"
  resa = "https://www.beds24.com/booking2.php?ownerid=69944&propid=162238"
  instagram = "https://instagram.com/les_cimesblanches/"